// IGNORE

JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
	src/Interface.java \
	src/Adjusters.java \
	src/Agents.java \
	src/Claims. java \
	src/Customer.java \
	src/InsuredItems.java \
	src/Payments.java \
	src/Policies.java \

MAIN = Interface

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class